logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 150000

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://registry:8761/eureka/

server:
  error:
    include-message: always
    include-binding-errors: always